server:
  port: 8081
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
spring:
  application:
    name: web-service
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bpb
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9009
  endpoint:
    health:
      show-details: always
