server:
  port: 8082
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://somedomain.com:3306/bpb
    username: encryptedusername
    password: encryptedpassword
management:
  endpoints:
    web:
      exposure:
        include: '*'