spring:  
  jpa:  
    hibernate:  
      ddl-auto: update  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL8Dialect  
  datasource:  
    url: jdbc:mysql://localhost:3306/bpb  
    username: root  
    password: root